apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bidscoin
  annotations:
    github.com/project-slug: dzemanov/bidscoin
spec:
  type: other
  lifecycle: unknown
  owner: user:default/dzemanov
