[metadata]
name = 'bidscoin'
version = '3.7.0-dev'
description = 'Map source-level neuroimaging data onto a BIDS data structure'
author = 'Marcel Zwiers'
author_email = 'm.zwiers@donders.ru.nl'
license = 'GPL3'
url = 'https://github.com/Donders-Institute/bidscoin'

[requires]
python_version = ['3.8', '3.9']

[options.extras_require]
    bioread = { version = "^1.0.5"}
    pymatreader = { version = "^0.0.24"}
    duecredit = {version = "^0.9.1"}
    phys2bids = {version = "^2.0.0"}

[build-system]
requires = ['setuptools', 'wheel']
