[metadata]
name = 'bidscoin'
version = '3.7.0-dev'
description = 'Map source-level neuroimaging data onto a BIDS data structure'
author = 'Marcel Zwiers'
author_email = 'm.zwiers@donders.ru.nl'
license = 'GPL3'
url = 'https://github.com/Donders-Institute/bidscoin'

[requires]
python_version = ['3.8', '3.9']

[options.extras_require]
phys2bids =
    bioread >=1.0.5
    pymatreader >=0.0.24
    duecredit
    phys2bids >=2.0.0, <3.0.0

[build-system]
requires = ['setuptools', 'wheel']
