name: CI
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        # os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install dcm2niix posix
        if: runner.os != 'Windows'
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            mkdir dcm2niix_install/ && cd dcm2niix_install/
            curl -fLO https://github.com/rordenlab/dcm2niix/releases/download/v1.0.20220720/dcm2niix_lnx.zip
            unzip dcm2niix*.zip
          echo "${{ github.workspace }}/dcm2niix_install/" >> $GITHUB_PATH
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install dcm2niix
          fi

      - name: Install dcm2niix windows
        if: runner.os == 'Windows'
        run: |
          curl -fLO https://github.com/rordenlab/dcm2niix/releases/latest/download/dcm2niix_win.zip
          powershell -command "Expand-Archive dcm2niix_win.zip"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install .[all]

      - name: Tests with pytest
        run: |
           pytest tests
#          make test
