name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[all]
          pip install pytest
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
      - name: Install dcm2niix
        run: |
          conda env update --file environment.yml --name base
          conda install -c conda-forge dcm2niix
      - name: Test with pytest
        run: |
          pytest
